<?php 


if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group(array(
    'key' => 'group_697b846d25056',
    'title' => __('ArcGIS Module Settings', 'modularity-arcgis-map'),
    'fields' => array(
        0 => array(
            'key' => 'field_697b854beb4da',
            'label' => __('Settings', 'modularity-arcgis-map'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
            'selected' => 0,
        ),
        1 => array(
            'key' => 'field_69b25f6793498',
            'label' => __('Map position', 'modularity-arcgis-map'),
            'name' => 'coordinates',
            'aria-label' => '',
            'type' => 'arcgis_open_street_map',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'listen_default_location' => 1,
            'allow_in_bindings' => 0,
        ),
        2 => array(
            'key' => 'field_697b85e52e453',
            'label' => __('Height in pixels', 'modularity-arcgis-map'),
            'name' => 'height',
            'aria-label' => '',
            'type' => 'number',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 500,
            'min' => 300,
            'max' => 1000,
            'allow_in_bindings' => 0,
            'placeholder' => '',
            'step' => '',
            'prepend' => '',
            'append' => __('px', 'modularity-arcgis-map'),
        ),
        3 => array(
            'key' => 'field_697b912b65b8d',
            'label' => __('Show marker', 'modularity-arcgis-map'),
            'name' => 'show_marker',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'allow_in_bindings' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 1,
        ),
        4 => array(
            'key' => 'field_map_description',
            'label' => __('Description', 'modularity-arcgis-map'),
            'name' => 'map_description',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'allow_in_bindings' => 0,
        ),
        5 => array(
            'key' => 'field_697b853feb4d9',
            'label' => __('Advanced', 'modularity-arcgis-map'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
            'selected' => 0,
        ),
        6 => array(
            'key' => 'field_697b846d20973',
            'label' => __('Portal URL', 'modularity-arcgis-map'),
            'name' => 'portal_url',
            'aria-label' => '',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
        ),
        7 => array(
            'key' => 'field_697b849b20974',
            'label' => __('Theme URL', 'modularity-arcgis-map'),
            'name' => 'theme_url',
            'aria-label' => '',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
        ),
        8 => array(
            'key' => 'field_697b8512eb4d8',
            'label' => __('Map ID', 'modularity-arcgis-map'),
            'name' => 'map_id',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        9 => array(
            'key' => 'field_697b857deb4dc',
            'label' => __('Marker', 'modularity-arcgis-map'),
            'name' => 'marker',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'uploader' => '',
            'return_format' => 'url',
            'library' => 'all',
            'acfe_thumbnail' => 0,
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'allow_in_bindings' => 0,
            'preview_size' => 'medium',
        ),
        10 => array(
            'key' => 'field_697b8e9873f8c',
            'label' => __('Marker width', 'modularity-arcgis-map'),
            'name' => 'marker_width',
            'aria-label' => '',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'min' => 20,
            'max' => 100,
            'allow_in_bindings' => 0,
            'placeholder' => 27,
            'step' => '',
            'prepend' => '',
            'append' => __('px', 'modularity-arcgis-map'),
        ),
        11 => array(
            'key' => 'field_697b8eaf73f8d',
            'label' => __('Marker height', 'modularity-arcgis-map'),
            'name' => 'marker_height',
            'aria-label' => '',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'min' => 20,
            'max' => 100,
            'allow_in_bindings' => 0,
            'placeholder' => 40,
            'step' => '',
            'prepend' => '',
            'append' => __('px', 'modularity-arcgis-map'),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-arcgis-map',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/arcgis-map',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
));

}