<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_697b7f6b93f76',
    'title' => __('ArcGIS settings', 'modularity-arcgis-map'),
    'fields' => array(
        0 => array(
            'key' => 'field_697b7f6c0b121',
            'label' => __('SDK URL', 'modularity-arcgis-map'),
            'name' => 'sdk_url',
            'aria-label' => '',
            'type' => 'url',
            'instructions' => __('The URL to the ArcGIS JavaScript SDK used to render maps in the module.', 'modularity-arcgis-map'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
        ),
        1 => array(
            'key' => 'field_697b7f9f0b122',
            'label' => __('Theme URL', 'modularity-arcgis-map'),
            'name' => 'theme_url',
            'aria-label' => '',
            'type' => 'url',
            'instructions' => __('The URL to the ArcGIS theme stylesheet used for map components. This controls the visual styling of the map interface and should normally match the SDK version.', 'modularity-arcgis-map'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
        ),
        2 => array(
            'key' => 'field_697b8184fd8ef',
            'label' => __('Default portal URL', 'modularity-arcgis-map'),
            'name' => 'portal_url',
            'aria-label' => '',
            'type' => 'url',
            'instructions' => __('The ArcGIS Portal or ArcGIS Online URL used to retrieve map resources. This portal will be used as the default source when loading web maps or other ArcGIS content.', 'modularity-arcgis-map'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
        ),
        3 => array(
            'key' => 'field_697b81acfd8f0',
            'label' => __('Default map ID', 'modularity-arcgis-map'),
            'name' => 'map_id',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => __('The default ArcGIS Web Map ID used when no map is explicitly defined in the module settings. This allows a predefined map to be displayed automatically.', 'modularity-arcgis-map'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        4 => array(
            'key' => 'field_697b7fed7172a',
            'label' => __('Default marker', 'modularity-arcgis-map'),
            'name' => 'marker',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => __('The default marker icon used for map locations when no custom marker is specified.
Provide a URL to an image file that will be used as the map marker or leave blank to use the provided.', 'modularity-arcgis-map'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'allow_in_bindings' => 0,
            'preview_size' => 'medium',
        ),
        5 => array(
            'key' => 'field_69b259ee20c33',
            'label' => __('Default map position', 'modularity-arcgis-map'),
            'name' => 'start_position',
            'aria-label' => '',
            'type' => 'arcgis_open_street_map',
            'instructions' => __('The default map view used when a module is first created and no map position has been configured. This defines the initial center coordinates and zoom level displayed in the map.', 'modularity-arcgis-map'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'listen_default_location' => 0,
            'allow_in_bindings' => 0,
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'modularity-arcgis-map-settings',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
));
}